<a href="https://colab.research.google.com/github/NAVYALEKSHM2/Datascience/blob/main/mtrxsvd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from numpy import array 
from scipy.linalg import svd

A=array([[1,2],[3,4],[5,6]])
print("A: \n%s" %A)

u,s,vt=svd(A)

print("\nu:%s " %u)
print("\ns:%s " %s)
print("\nvt:%s " %vt)

A: 
[[1 2]
 [3 4]
 [5 6]]

u:[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]] 

s:[9.52551809 0.51430058] 

vt:[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]] 
