<a href="https://colab.research.google.com/github/NAVYALEKSHM2/Datascience/blob/main/mtrxoperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

a= np.array([1,2,3])
print("type: %s" %type(a))
print("shape: %s" %a.shape)

print("\nArray a= ")
print(a)
a[0]=5
print("After changing first element:")
print(a)

b=np.array([[1,2,3],[4,5,6]])
print("\n shape of b:" ,b.shape)

print(b[0,0],b[0,1],b[1,0])

a=np.zeros((2,2))
print("\nAll zero matrix: %s" %a)

b=np.ones((1,2))
print("\nAll one matrix: %s" %b)

d=np.eye(2)
print("\nIdentity matrix: %s" %d)

e=np.random.random((2,2))
print("\nRandom matrix: %s" %d)

print("Vectorized Sum \n ")
x = np.array([[1,2], [3,4]])
print("Array x:\n %s" %x)
print("\nsum : %s" %np.sum(x))
print("Sum axis=0 :%s" %np.sum(x,axis=0))
print("Sum axis=1 :%s" %np.sum(x,axis=1))

a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[10,11]])
dp=np.dot(a,b)
print("\nDot product= %s" %dp)

a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[10,11]])
op=np.outer(a,b)
print("\nOuter product= %s" %op)

a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[9,10]])
ep=np.multiply(a,b)
print("\nElement wise product= %s" %ep)



type: <class 'numpy.ndarray'>
shape: 3

Array a= 
[1 2 3]
After changing first element:
[5 2 3]

 shape of b: (2, 3)
1 2 4

All zero matrix: [[0. 0.]
 [0. 0.]]

All one matrix: [[1. 1.]]

Identity matrix: [[1. 0.]
 [0. 1.]]

Random matrix: [[1. 0.]
 [0. 1.]]
Vectorized Sum 
 
Array x:
 [[1 2]
 [3 4]]

sum : 10
Sum axis=0 :[4 6]
Sum axis=1 :[3 7]

Dot product= [[27 30]
 [78 87]]

Outer product= [[ 7  8 10 11]
 [14 16 20 22]
 [28 32 40 44]
 [35 40 50 55]]

Element wise product= [[ 7 16]
 [27 40]]
