<a href="https://colab.research.google.com/github/NAVYALEKSHM2/Datascience/blob/main/mtrxprdct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
a=np.arange(10000)
b=np.arange(10000)


dp=np.dot(a,b)
print("Dot product: %s\n" %dp)

op=np.outer(a,b)
print("Outer product: %s\n" %op)

ep=np.multiply(a,b)
print("Element wise product: %s\n" %ep)

Dot product: 333283335000

Outer product: [[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]]

Element wise product: [       0        1        4 ... 99940009 99960004 99980001]



In [7]:
#DOT PRODUCT
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[9,10]])

dp=np.dot(a,b)
print("Dot product= %s" %dp)


Dot product= [[25 28]
 [57 64]]


In [6]:
#OUTER PRODUCT
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[9,10]])

op=np.outer(a,b)
print("Outer product= %s" %op)


Outer product= [[ 7  8  9 10]
 [14 16 18 20]
 [21 24 27 30]
 [28 32 36 40]]


In [9]:
#ELEMENT WISE PRODUCT

import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[7,8],[9,10]])

ep=np.multiply(a,b)
print("element wise product= %s" %ep)

element wise product= [[ 7 16]
 [27 40]]
